name: Deploy

on:
  push:
    branches:
     - dev
     - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set env for building and deploying docker image
      env: 
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        if [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
          echo "ECR_REPOSITORY=action-test-dev" >> "$GITHUB_ENV"
        else
          echo "ECR_REPOSITORY=action-test-prod" >> "$GITHUB_ENV"
        fi
        sed -i.bak 's#ECR_URI#'"$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"'#' ./k8s/deployment.yaml
          
    - name: Build, tag, and push image to AWS ECR
      run: |
        # Build a docker container and push it to ECR
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Deploy
      run: |
        aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.AWS_CLUSTER }}
        kubectl apply -f ./k8s/deployment.yaml -f ./k8s/service.yaml
